spring:
  application:
    name: conbook
  datasource:
    url: jdbc:mariadb://localhost:3306/conbook
    username: margin
    password: mun1103
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
#        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  kafka:
    consumer:
      group-id: conbook.concert-booking.notification
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

springdoc:
  swagger-ui:
    tags-sorter: alpha
    enabled: true
    path: /api
  api-docs:
    enabled: true

logging:
  file:
    name: logs/conbook.log
#  level:
#    org.springframework.orm: debug
#    io.hhplus.conbook: debug