spring:
  application:
    name: conbook
  datasource:
    url: jdbc:mariadb://localhost:3306/conbook
    username: margin
    password: mun1103
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
springdoc:
  swagger-ui:
    tags-sorter: alpha
    enabled: true
    path: /api
  api-docs:
    enabled: true

#logging:
#  level:
#    org.springframework.orm: debug
#    io.hhplus.conbook: debug