spring:
  application:
    name: conbook
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
springdoc:
  swagger-ui:
    tags-sorter: alpha
    enabled: true
    path: /api
  api-docs:
    enabled: true

