drop table if exists payment
drop table if exists booking
drop table if exists token_history
drop table if exists seat
drop table if exists concert_schedule
drop table if exists concert
drop table if exists user_point
drop table if exists users
drop table if exists token